feat: add multi select element
uwblueprint/jump-math pull request #174
Opened 2023-03-23 01:54 UTC by JennaXiao3

## Notion ticket link

[Add multi-select component to Question Editor](https://www.notion.so/uwblueprintexecs/Add-multi-select-component-to-Question-Editor-125650fdb8be4b0db5cf66e95fd5b1c3?pvs=4)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-03-27 20:50 UTC, joyce-shi requested changes
looks great! i'm happy you got it working. 🤠  but instead of duplicating the code from the Multiple Choice logic, would you be able to reuse code where possible?

2023-03-27 23:22 UTC, JennaXiao3 commented
> looks great! i'm happy you got it working. 🤠 but instead of duplicating the code from the Multiple Choice logic, would you be able to reuse code where possible?
> 
> in particular, `MultiSelectModal`, `MultiSelectOption`, `SelectOptionCount`, `MultiSelectData` and `updatedMultiSelectOption` are almost exact duplicates of their Multiple Choice counterparts!

If I want to reuse it, should I rename the components?

2023-03-27 23:50 UTC, joyce-shi commented
> > looks great! i'm happy you got it working. 🤠 but instead of duplicating the code from the Multiple Choice logic, would you be able to reuse code where possible?
> > in particular, `MultiSelectModal`, `MultiSelectOption`, `SelectOptionCount`, `MultiSelectData` and `updatedMultiSelectOption` are almost exact duplicates of their Multiple Choice counterparts!
> 
> If I want to reuse it, should I rename the components?

use your best judgement! feel free to rename existing files, move things around, whatever you think makes for the cleanest code! (:

2023-03-28 03:18 UTC, JennaXiao3 commented
> > > looks great! i'm happy you got it working. 🤠 but instead of duplicating the code from the Multiple Choice logic, would you be able to reuse code where possible?
> > > in particular, `MultiSelectModal`, `MultiSelectOption`, `SelectOptionCount`, `MultiSelectData` and `updatedMultiSelectOption` are almost exact duplicates of their Multiple Choice counterparts!
> > 
> > 
> > If I want to reuse it, should I rename the components?
> 
> use your best judgement! feel free to rename existing files, move things around, whatever you think makes for the cleanest code! (:

I've added a state called "isMultiSelect" and added necessary props to some multiple choices components when needed. Is this okay? If so, I will change the names of the multiple choice components to "multichoice" or something to show that it's used by multiple choice and multi-select

2023-03-28 03:37 UTC, joyce-shi commented on frontend/src/components/pages/admin/QuestionPage.tsx
> +          setIsMultiSelect,
I think we can keep the naming consistent here!

```suggestion
          showAddMultiSelectModal,
          setShowAddMultiSelectModal,
```

2023-03-28 04:14 UTC, joyce-shi reviewed
looks a lot better! left some thoughts (:

i think overall, i would prefer if we kept the logic to show multiple choice and multi select separate! i.e can have separate `setShowMultipleChoiceModal` and `setShowMultiSelectModal` values (but should not have both set to true at the same time). left some more detailed thoughts on this below!

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/pages/admin/QuestionPage.tsx
> +          setIsMultiSelect,
I think we can change the naming here to be consistent with the other question elements!

```suggestion
          showAddMultiSelectModal,
          setShowAddMultiSelectModal,
```

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/QuestionSidebarItem.tsx
> +            setIsMultiSelect(true);
I think we can just set one to true and if either are true, we can show the modal! i think you'll have to update `AddMultipleChoiceModal` where that logic is defined 🤔 
```suggestion
            setShowAddMultiSelectModal(true);
```

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
> +          </VStack>
I think **lines 39 - 51** and **lines 55 - 67** are identical, can refactor them into a common constant?

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
> +  isMultiSelect,
nit: instead of having a prop `isMultiSelect`, can this component have a `type` prop that is of type `QuestionElementType.MULTIPLE_CHOICE | QuestionElementType.MULTI_SELECT` instead?

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/AddMultipleChoiceModal.tsx
> +  const multiData = isMultiSelect
nit: `multiData` -> `type` and then i think you can use shorthand

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/MultipleChoiceModal.tsx
> +    } else if (!isMultiSelect && correctOptionCount > 1) {
nit: instead of `!isMultiSelect` can we use `isMultipleChoice` here for more better readability?

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/EditMultipleChoiceModal.tsx
>        onConfirm={updateMultipleChoiceElement}
same as above! if we could rename this modal to `EditMultiDataModal.tsx` or something, that would be awesome! and the folder should probably be renamed to `multi-option` as well!

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/MultipleChoiceModal.tsx
>          {noCorrectOptionError && (
same as above! `MultipleChoiceModal` -> `MultiOptionModal`!

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/QuestionElementItem.tsx
> +          data={data as MultipleChoiceData}
would you be able to rename the type to something more general since we are using it for both cases? maybe something like `MultiOptionData`!

2023-03-28 04:14 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
> +        isMultiSelect={isMultiSelect}
nit: `isMultiSelect ` ->`type`

2023-03-28 04:18 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/AddMultipleChoiceModal.tsx
>        isOpen={showAddMultipleChoiceModal}
I think instead you can do something like `isMultipleChoice ? showAddMultipleChoiceModal : showAddMultiSelectModal`

2023-03-30 00:50 UTC, JennaXiao3 commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/AddMultipleChoiceModal.tsx
> +  const multiData = isMultiSelect
Do you mean 
```type multiData = showAddMultiSelectModal ? QuestionElementType.MULTI_SELECT : QuestionElementType.MULTIPLE_CHOICE;```

This doesn't seem to work for some reason...

2023-03-30 01:54 UTC, joyce-shi requested changes
looks so good! just left a couple comments about renaming the components that are used by both **Multiple Choice** and **Multi-Select** to something general.

2023-03-30 01:54 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
> +
is this constant used somewhere? 👀

2023-03-30 01:54 UTC, joyce-shi commented on frontend/src/components/question-creation/QuestionElementItem.tsx
> +          data={data as MultipleChoiceData}
Could you update `MultipleChoiceData` -> `MultiOptionData` or something like that?

2023-03-30 01:54 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
>  const MultipleChoiceElement = ({
Could you update `MultipleChoiceElement` -> `MultiOptionElement` or something like that?

2023-03-30 01:54 UTC, joyce-shi commented on frontend/src/components/question-creation/question-elements/modals/multiple-choice/AddMultipleChoiceModal.tsx
>    };
Could you update `AddMultipleChoiceModal` -> `AddMultiOptionModal` or something like that? also all the references to **Multiple Choice** in this file! & same for the `EditMultipleChoiceModal` and `MultipleChoiceModal`. You can also update the folder naming!

2023-03-30 02:07 UTC, JennaXiao3 commented on frontend/src/components/question-creation/question-elements/MultipleChoiceElement.tsx
> +
WHOOPS

2023-04-02 17:03 UTC, joyce-shi approved these changes
LGTM

2023-04-04 03:56 UTC, merged