add get testSession by id
uwblueprint/jump-math pull request #22
Opened 2022-07-10 14:55 UTC by brian386

## Notion ticket link

[Get test session by id](https://www.notion.so/uwblueprintexecs/47bf4727a2444bccad4a91952898b8f3?v=9658436bf9be409e90581631a7155f16&p=4d97cfdb81de406a9a512b04de4ea482)

## Implementation description
* Query the database for test session with specific id

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-11 00:37 UTC, carissa-tang requested changes
nice work! added few comments. just make sure your code is consistent with the rest of the service once https://github.com/uwblueprint/jump-math/pull/25 is merged (there's some helper functions you can use) and remember to run `yarn fix`

2022-07-11 00:37 UTC, carissa-tang commented on backend/services/interfaces/testSessionService.ts
> +  getTestSessionById(
Add comments to document `getTestSessionById` - you can follow the format of the other function

2022-07-13 20:58 UTC, brian386 commented
> 

hello! when I ran `yarn fix` it changed the formatting of some of the starter code files. Should I also commit these?

2022-07-14 23:48 UTC, carissa-tang commented
> > 
> 
> hello! when I ran `yarn fix` it changed the formatting of some of the starter code files. Should I also commit these?

ya sure, if it's just formatting

2022-07-15 14:11 UTC, carissa-tang requested changes

2022-07-15 14:11 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +        throw new Error(`Entity id ${id} not found`);
```suggestion
        throw new Error(`Test session ${id} not found`);
```

2022-07-15 14:11 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +      Logger.error(`Failed to get entity. Reason = ${getErrorMessage(error)}`);
```suggestion
      Logger.error(`Failed to get test session. Reason = ${getErrorMessage(error)}`);
```

2022-07-15 14:11 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +    return {
instead of this, you can call smth like `return await this.mapTestSessionsToTestSessionDTOs([testSession])[0];` to avoid DRY code. or lmk if there's a cleaner way to refactor it

2022-07-15 14:11 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +  it("getTestSession", async () => {
for consistency sake, could you refactor this code like the other tests?
`await MgTestSession.create(mockTestSession);`
`const res = await testSessionService.getTestSessionById(mockTestSession.id);`
`assertResponseMatchesExpected(mockTestSession, res);`
 `assertResultsResponseMatchesExpected(mockTestSession, res);`

2022-07-20 03:17 UTC, carissa-tang requested changes

2022-07-20 03:17 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +const { ObjectId } = require("mongodb");
i think you can remove this now? if you run `yarn fix` it should indicate that

2022-07-20 03:17 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +    const res = await testSessionService.getTestSessionById(savedTestSession.id,);
```suggestion
    const res = await testSessionService.getTestSessionById(savedTestSession.id);
```

2022-07-21 01:56 UTC, carissa-tang approved these changes
nice work!

2022-07-21 13:14 UTC, merged