Implement Method For Getting School By Id
uwblueprint/jump-math pull request #33
Opened 2022-07-22 00:53 UTC by mahadzaryab1

## Notion ticket link

[Get school by id](https://www.notion.so/uwblueprintexecs/Get-school-by-id-55b7836244394df8bb1900a915526f7f)

## Implementation description
* Implemented method to get school by id 
* Added tests for new method

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-22 01:13 UTC, carissa-tang requested changes

2022-07-22 01:13 UTC, carissa-tang commented on backend/services/implementations/__tests__/schoolService.test.ts
> +    const savedSchool = await SchoolModel.create(testSchool);
could we use `testSchools[0]` instead of `testSchool` just to avoid making new variables for every function?

2022-07-22 01:31 UTC, carissa-tang approved these changes
lgtm!

2022-07-27 16:51 UTC, joyce-shi approved these changes
LGTM! 🛳

2022-07-28 22:33 UTC, merged