Omar/delete test by
uwblueprint/jump-math pull request #34
Opened 2022-07-22 00:57 UTC by obaranek

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Delete-test-0cce32099ffb4bc99409082ebd983a00)

## Implementation description
* created interface for deleteTest
* implemented deleteTest
* added two tests to test deleteTest behaviour when test id is found and is missing.

## Steps to test
1.run yarn test and make sure both tests, "deleteTest" and "deleteTest" when id not found", pass

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-23 13:49 UTC, carissa-tang reviewed
are we doing soft deletes?

2022-07-23 13:49 UTC, carissa-tang commented on backend/services/interfaces/testService.ts
> +   * delete a TestSession with the given id, return deleted id
```suggestion
   * delete a Test with the given id, return deleted id
```

2022-07-23 17:32 UTC, obaranek commented
@joyce-shi are we 

> are we doing soft deletes?

@joyce-shi

2022-07-27 16:52 UTC, joyce-shi commented
> > are we doing soft deletes?
> 
> @joyce-shi

let's do hard deletes for the sake of simplicity right now. if we find it's an issue we can revisit in the future

2022-07-27 16:55 UTC, joyce-shi requested changes
LGTM, left a small comment re: error clarity.
One quick thing: I noticed that in this PR, there's a lot of changes highlighted, where there aren't really any changes (i.e spacing, line breaks). Just wanted to double check that you ran the linter before opening this?

2022-07-27 16:55 UTC, joyce-shi commented on backend/services/implementations/testService.ts
> +        `Failed to delete entity. Reason = ${getErrorMessage(error)}`,
nit: let's change this to `Failed to delete test` for clarity

2022-08-07 19:45 UTC, joyce-shi approved these changes

2022-08-07 22:53 UTC, merged