feat: Compute Top Performing Students
uwblueprint/jump-math pull request #446
Opened 2023-07-08 19:54 UTC by wais-hundekar

## Notion ticket link

[Compute Top Performing Students](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* Implemented resolver, function and query to compute the top 5 students for a given testSessionId
<img width="1153" alt="Screenshot 2023-07-08 at 3 54 11 PM" src="https://github.com/uwblueprint/jump-math/assets/87676999/e4ac2937-46ce-4383-9053-36bc845361a7">

## Steps to test
1. Ensure existing tests are accurate
2. Call function on test sessions within the backend, (ensure expired date has passed)

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-07-12 01:48 UTC, carissa-tang requested changes

2023-07-12 01:48 UTC, carissa-tang commented on backend/graphql/resolvers/testSessionResolvers.ts
> +    getTop5StudentsByTestSessionId: (
```suggestion
    getTopFiveStudentsById: (
```
nit: rename function

2023-07-12 01:48 UTC, carissa-tang commented on backend/services/interfaces/testSessionService.ts
> +   * Get the top 5 best students for a test session
```suggestion
   * Get the top 5 students (based on test score) for a test session
```

2023-07-12 01:48 UTC, carissa-tang commented on frontend/src/APIClients/queries/TestSessionQueries.ts
> +    getTop5StudentsByTestSessionId(id: $getTop5StudentsByTestSessionIdId)
```suggestion
  query Query($id: ID!) {
    getTop5StudentsByTestSessionId(id: $id)
```

2023-07-12 01:48 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +      const results = testSession.results || [];
can you add types to all these variables?

2023-07-12 01:48 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +      const top5Students = sortedResults
```suggestion
      const topFiveStudents = sortedResults
```

2023-07-21 04:54 UTC, carissa-tang reviewed
few more comments

2023-07-21 04:54 UTC, carissa-tang commented on frontend/src/APIClients/queries/TestSessionQueries.ts
> +    gettop5StudentsById(id: $id)
```suggestion
    getTopFiveStudentsById(id: $id)
```

2023-07-21 04:54 UTC, carissa-tang commented on backend/services/implementations/testSessionService.ts
> +        throw new Error("Test session has not ended yet");
can we add the `testSessionId` into the error message?

2023-07-21 04:54 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +    testSessionService.getTestSessionById = jest
why do you need to mock this?

2023-07-22 15:33 UTC, wais-hundekar commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +    testSessionService.getTestSessionById = jest
good point!

2023-07-22 16:25 UTC, carissa-tang approved these changes
minor nits, but lgtm!

2023-07-22 16:25 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +
```suggestion
```

2023-07-22 16:25 UTC, carissa-tang commented on backend/services/implementations/__tests__/testSessionService.test.ts
> +    ).rejects.toThrowError("Test session has not ended yet");
```suggestion
    ).rejects.toThrowError(`Test session has not ended yet. testSessionId: ${savedTestSession.id}`);
```

2023-07-22 17:31 UTC, merged