feat: edit test sessions
uwblueprint/jump-math pull request #568
Opened 2023-09-06 00:24 UTC by carissa-tang

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-09-06 00:47 UTC, carissa-tang commented on frontend/src/components/pages/teacher/DisplayAssessmentsPage.tsx
> -                      classroomName={session.classroomName ?? ""}
`classroomName` already passed via `session` object

2023-09-06 04:06 UTC, jfdoming requested changes
awesome 💯 ~~could we add some validation to the backend to make sure we're really only able to update the two fields users are allowed to update when it comes to active sessions? You could do a two-pass update, where the first pass runs `findOneAndUpdate` for only the `endDate` and `notes` fields with a query of `endDate` against `now` to check whether it's still active, and the second pass `findOneAndUpdate` for the remaining fields with a query of `startDate` against `now` to check whether it's active~~ LOL I should really check your other PRs first. Other comments are still relevant I think though!

2023-09-06 04:06 UTC, jfdoming commented on backend/graphql/resolvers/testSessionResolvers.ts
> +      { id, testSession }: { id: string; testSession: TestSessionRequestDTO },
Is it possible to get the ID off of the DTO instead of passing it in separately? not sure if there's a preference

2023-09-06 04:06 UTC, jfdoming commented on frontend/src/components/common/table/Table.tsx
> +  isDisabled = false,
Following the pattern we've used for rows so far, maybe we should consider adding this prop to the row instead of the table?

2023-09-06 04:06 UTC, jfdoming commented on frontend/src/components/teacher/session-creation/DistributeAssessmentButton.tsx
> +    refetchQueries: [{ query: GET_TEST_SESSIONS_BY_TEACHER_ID }],
nit: we should change this and the one above to use `getQueryName` so we can avoid worrying about extra parameters in the future

2023-09-06 04:06 UTC, jfdoming commented on frontend/src/components/teacher/session-creation/DistributeAssessmentButton.tsx
> +      showToast({
Ah yes one more modal I forgot to refactor :')

2023-09-06 04:06 UTC, jfdoming commented on frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
> +  notes?: string;
There are enough props here that I'm wondering if we should just pass down `session` using the response type directly. That way we don't have to enumerate all of these props. Thoughts?

2023-09-06 06:56 UTC, carissa-tang commented on backend/graphql/resolvers/testSessionResolvers.ts
> +      { id, testSession }: { id: string; testSession: TestSessionRequestDTO },
hm our other update functions pass id separately from RequestDTO so might make more sense to keep it that way?

2023-09-09 05:40 UTC, jfdoming approved these changes

2023-09-09 05:43 UTC, merged