fix: fix test session list item UI
uwblueprint/jump-math pull request #574
Opened 2023-09-10 18:55 UTC by carissa-tang

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-09-10 19:21 UTC, carissa-tang commented
I refactored the component bc it was pretty hard for me to read, but we can revert if you hate it lol. Also I was playing around with moving the access code to the right but not sure with how it looks in the table, so just added extra space for now. lmk which you prefer!

<img width="696" alt="image" src="https://github.com/uwblueprint/jump-math/assets/69697180/44a1954f-c19b-4365-b8fa-c1b65055eb4f">
<img width="1431" alt="image" src="https://github.com/uwblueprint/jump-math/assets/69697180/2acc7f51-c498-4162-a10c-d68f663f34cf">
<img width="1436" alt="image" src="https://github.com/uwblueprint/jump-math/assets/69697180/167c0ef1-4aae-4634-8f5b-7ff6b8b36086">

2023-09-10 22:00 UTC, jfdoming requested changes
Left a couple of comments I think we should think about. Also, I really like how moving the code to the right side looks! However, I think with the status label it looks a bit weird. Could we actually move the status label all the way to the left along with moving the code to the right? It would take the place of the "classroom" tag since those two tags never appear at the same time here

2023-09-10 22:00 UTC, jfdoming commented on frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
> +          inClassroomPage
Wondering if we need this flag explicitly? I think before we were just using the nullish-ness of `className` for the same purpose, and having a flag providing the same information seems a little brittle

2023-09-10 22:00 UTC, jfdoming commented on frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
> +        gap={6}
I'm a little worried about these extra props drifting from the corresponding `HStack` below (which was why we used the `isDisabled` prop on the tooltip before). Maybe add a `WRAPPER_PROPS` constant above and spread it onto the children? lmk your thoughts though, seems like there might be a better way

2023-09-10 22:00 UTC, jfdoming commented on frontend/src/components/teacher/view-sessions/TestSessionListItemBody.tsx
> +          noOfLines={1}
Adding this prop means that the text is truncated on small screens => teachers can't always read the date in full. Could we either (a) revert the change, (b) add a tooltip for the date (seems ugly though), or (c) consider other options to make it fully visible?

2023-09-10 22:41 UTC, carissa-tang commented on frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
> +          inClassroomPage
`className` now exists in all pages bc it's passed down for editing

2023-09-10 22:43 UTC, jfdoming commented on frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
> +          inClassroomPage
Wait what do we need it for when editing? I'd think we would only need classId for the currently-selected class?

2023-09-11 01:36 UTC, carissa-tang commented on frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
> +          inClassroomPage
we display it in the review page

2023-09-11 01:37 UTC, jfdoming commented on frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
> +          inClassroomPage
oh ok

2023-09-11 01:53 UTC, carissa-tang commented on frontend/src/components/teacher/view-sessions/TestSessionListItemBody.tsx
> +          noOfLines={1}
one idea is to show untruncated on hover, but we don't really use that anywhere else so i'll just revert for now

2023-09-11 06:06 UTC, jfdoming approved these changes

2023-09-11 06:32 UTC, merged