Admin Users Query
uwblueprint/jump-math pull request #68
Opened 2022-11-10 01:53 UTC by Boyazhang1

## Notion ticket link

[Admin Users Query] https://www.notion.so/uwblueprintexecs/47bf4727a2444bccad4a91952898b8f3?v=9658436bf9be409e90581631a7155f16&p=5b06976a90ca44a4b4393c3e59bcf0b2&pm=s

## Implementation description
* created the query on TeacherPage

## Steps to test
1. Go to TeacherPage.tsx, add the line "console.log(adminUsers)"
2. Navigate to localhost:3000/teachers, view the console, and verify the array is in the format
[{firstName, lastName, email}]

## What should reviewers focus on?
* query is formatted properly, handles everything required

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-11-11 02:54 UTC, joyce-shi requested changes
Awesome work! 🔥 Left some quick comments. 

One thing: I know we chatted about this earlier, but could we actually put the contents of this query in a separate page? You can just create a new page and name it whatever. Then, when you call the data, you can also pass it to the `AdminTable` component, so that we can test it! 

I know Victor's ticket overlaps a bit, but we probably shouldn't be putting random things in random pages when we don't know where to put them LOL. Totally my bad, I should have said this when we last chatted!

2022-11-11 02:54 UTC, joyce-shi commented on frontend/src/components/pages/TeacherPage.tsx
> +  const ADMIN_USERS = gql`
Sorry, I should have said something earlier, but I think this query already exists under the `RemoveUserModal` component. Could you refactor that to a common folder (maybe create a new `queries` folder under `APIClients`) and then use the same one?

2022-11-11 02:54 UTC, joyce-shi commented on frontend/src/components/pages/TeacherPage.tsx
> +  const [adminUsers, setAdminUsers] = useState<AdminUser[]>();
I'm not too sure if we need to use state in this case. I think we may just be able to stick to the style provided by the [documentation](https://www.apollographql.com/docs/react/data/queries#executing-a-query) on Querying in GraphQL? That is, the `const { loading, error, data } = useQuery(...` format. Then, you can just pass `data` to the `AdminTable` component that you built earlier!

Instead of state, `refetchQueries` can be used to handle changes to the list of admin users. This can be called in any mutation that modifies the data that you're querying for here. This should already be implemented in the `RemoveUser` component! You can read more on this [here](https://www.apollographql.com/blog/apollo-client/caching/when-to-use-refetch-queries/).

P.S: Would you be able to check with design to see if there should be loading and error states here?

2022-11-17 06:03 UTC, joyce-shi requested changes
left some teeny tiny comments! should only take a min to address (: awesome work!!!

2022-11-17 06:03 UTC, joyce-shi commented on frontend/src/components/pages/AdminTablePage.tsx
> +      </>
what are your thoughts on refactoring the loading state into a variable above?

2022-11-17 06:03 UTC, joyce-shi commented on frontend/src/components/pages/AdminTablePage.tsx
> +      </>
same with the error state!

2022-11-17 06:03 UTC, joyce-shi commented on frontend/src/components/pages/AdminTablePage.tsx
> +            lastName: user.lastName,
nit: is it necessary to split up `user`? does `data?.usersbyRole?.map((user: AdminUser) => user)` or something similar work?

2022-11-17 06:03 UTC, joyce-shi commented on frontend/src/components/pages/AdminTablePage.tsx
> +import WarningIcon from "../../assets/warning-icon.png";
I think we use the `eva` icon pack in our codebase and design system! Would you be able to import the correct icon from that library into the `icons.tsx` file and use that here?

2022-11-18 05:17 UTC, Boyazhang1 commented on frontend/src/components/pages/AdminTablePage.tsx
> +            lastName: user.lastName,
I think so because the query attaches an id to each user for some reason, but the frontend type doesn't have ID

2022-11-18 16:04 UTC, joyce-shi approved these changes
LGTM!

2022-11-18 16:36 UTC, merged