feat: teacher signup page 4
uwblueprint/jump-math pull request #90
Opened 2022-12-08 05:30 UTC by j985chen

## Notion ticket link

[Teacher Signup - Page 4 - Set Password](https://www.notion.so/uwblueprintexecs/Teacher-Signup-Page-4-Set-Password-f597ccec8b4d43e4a5a331c3e1b85bfc)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-12-11 23:21 UTC, joyce-shi requested changes
Overall, LGTM! Super cool PR 😎. 

Question though: should we be using `useForm` features here? I believe that there is built in functionality for validation, errors and inputs? Specifically, I noticed that the `register` and `errors` props that are passed to the page are unused.

Additionally, I'm a bit confused about how state is generally stored in the `TeacherSignup` flow. Are we passing state collected from every page forward so that we can submit on this last page? And if so, where do we do this? i.e should we be doing something like [this](https://react-hook-form.com/advanced-usage#WizardFormFunnel)? 

cc @carissa-tang

2022-12-12 00:12 UTC, carissa-tang commented
> Overall, LGTM! Super cool PR 😎.
> 
> Question though: should we be using `useForm` features here? I believe that there is built in functionality for validation, errors and inputs? Specifically, I noticed that the `register` and `errors` props that are passed to the page are unused.
> 
> Additionally, I'm a bit confused about how state is generally stored in the `TeacherSignup` flow. Are we passing state collected from every page forward so that we can submit on this last page? And if so, where do we do this? i.e should we be doing something like [this](https://react-hook-form.com/advanced-usage#WizardFormFunnel)?
> 
> cc @carissa-tang

Yea, here's the doc on the built-in validation features https://react-hook-form.com/get-started#Applyvalidation not sure how restrictive it is tho.. I think if everything works as is we can leave it be. 

In terms of state, we are technically just working with one parent component `TeacherSignup`, which passes down the useForm functions so the child components can call them. To update a field, you can call `<input {...register('field')} />` or `setValue('field', 'value')` ([example in my pr](https://github.com/uwblueprint/jump-math/pull/88/files#diff-b5fb0cffdc6e0ba7a9bc3bcb3d3bf4ceeae975f2f09fdcb679fb35d91b3f6895R47)). You can query the form values using [getValues](https://react-hook-form.com/api/useform/getvalues) or [watch](https://react-hook-form.com/api/useform/watch). At the end, we can call `handleSubmit` which holds all the form data (in a param called `data`) and we can call our endpoints on `data`.

For this PR, I think you are just missing setting the value in `useForm`. To avoid refactoring, you can prob just call `setValues("password", password)`  before `handleSubmit`.

2022-12-12 19:16 UTC, BobShoaun requested changes
lgtm (lets get this MONEYY)

2022-12-12 19:16 UTC, BobShoaun commented on frontend/src/components/auth/TeacherSignup/TeacherSignupFour.tsx
> +  const onSubmit = () => {
where is the preventDefault?? rejected

2022-12-13 18:13 UTC, joyce-shi approved these changes
LGTM :D

2022-12-13 21:34 UTC, merged